### ISSUE TITLE
Error on clear_search in Blender 3.3.5 LTS - 'bpy_prop_collection[key]: key "WinMan" not found'

### ISSUE THREAD

**Issue by PLyczkowski** [sketchfab/blender-plugin#109]
Error content:

Error: Python: Traceback (most recent call last):
  File "C:\Users\PLyczkowski4\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\sketchfab-plugin-1-5-0\__init__.py", line 1840, in execute
    clear_search()
  File "C:\Users\PLyczkowski4\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\sketchfab-plugin-1-5-0\__init__.py", line 1827, in clear_search
    bpy.data.window_managers['WinMan']['result_previews'] = 0
KeyError: 'bpy_prop_collection[key]: key "WinMan" not found'

**Comment by jrEtbpsd5** [comment]
I have the same error message with Blender v3.3.x and 3.6.1 on Windows 10
![sketchfab_error_v3 6-200923](https://github.com/sketchfab/blender-plugin/assets/64588687/f2621255-7765-4827-b93f-b6bf172bf5d5)

**Comment by PadreZippo** [comment]
Fixed in **v1.7.1**. `clear_search` no longer assumes the window manager is named "WinMan", which caused the `KeyError` in headless/background sessions. https://github.com/sketchfab/blender-plugin/releases/tag/1.7.1

Closing as resolved. Thanks for the detailed traceback! 🙏

**Comment by jrEtbpsd5** [comment]
Thank you so much. I'd almost given up hope!
