### ISSUE TITLE
Plugin Will Not Install

### ISSUE THREAD

**Issue by redneckstudio** [sketchfab/blender-plugin#132]
Windows 11
Blender 4.1
I install the .zip file but when i try to enable i receive the following error message:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 444, in enable
    mod.register()
  File "C:\Users\ronal\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\sketchfab-plugin-1-6-0\__init__.py", line 2404, in register
    updateCacheDirectory(None, context=bpy.context)
  File "C:\Users\ronal\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\sketchfab-plugin-1-6-0\__init__.py", line 2294, in updateCacheDirectory
    if not os.path.exists(Config.SKETCHFAB_TEMP_DIR): os.makedirs(Config.SKETCHFAB_TEMP_DIR)
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 225, in makedirs
FileNotFoundError: [WinError 53] The network path was not found: '\\\\TEMP\\sketchfab_downloads'

**Comment by PadreZippo** [comment]
Fixed in **v1.7.1**. The add-on no longer crashes during registration when the download/cache directory can't be created (denied permissions, missing drive, unusual path characters) — it now falls back to the system temp directory and stays enabled. Please update: https://github.com/sketchfab/blender-plugin/releases/tag/1.7.1

Closing as resolved; reopen if it persists on 1.7.1. Thanks for the report! 🙏
