### ISSUE TITLE
Cannot import 3D model

### ISSUE THREAD

**Issue by joyanngitau** [sketchfab/blender-plugin#153]
Ubuntu 24

I tried importing a model using both the search feature and url method but I am getting these errors:
Search:
`Python: Traceback (most recent call last):
  File "/home/joyann/.config/blender/4.2/scripts/addons/sketchfab-plugin-1-6-1/__init__.py", line 1393, in modal
    bpy.context.scene.render.engine = "BLENDER_EEVEE"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bpy_struct: item.attr = val: enum "BLENDER_EEVEE" not found in ('BLENDER_EEVEE_NEXT', 'BLENDER_WORKBENCH', 'CYCLES')
`

URL:
`Python: Traceback (most recent call last):
  File "/home/joyann/.config/blender/4.2/scripts/addons/sketchfab-plugin-1-6-1/__init__.py", line 1393, in modal
    bpy.context.scene.render.engine = "BLENDER_EEVEE"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bpy_struct: item.attr = val: enum "BLENDER_EEVEE" not found in ('BLENDER_EEVEE_NEXT', 'BLENDER_WORKBENCH', 'CYCLES')
`

**Comment by joyanngitau** [comment]
Fixed it :)
Steps:

1. Went to the init.py file causing the error and to the specific line:

`/home/joyann/.config/blender/4.2/scripts/addons/sketchfab-plugin-1-6-1/__init__.py`

2. Switched `bpy.context.scene.render.engine = "BLENDER_EEVEE"` to `bpy.context.scene.render.engine = "BLENDER_EEVEE_NEXT"`

**Comment by MrHyplex9511** [comment]
In Blender 4.2 it was not working then i troubleshooted the problem cuz i am a skid.

I found out that if the error is fix line 1393, then open the innit.py file in the
(C:\Users\Your user\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\sketchfab-plugin-1-6-1/innit.py)
and go to line 1393. As shown below and

1392 if bpy.context.scene.render.engine not in ["CYCLES", "BLENDER_EEVEE"]:
1393 bpy.context.scene.render.engine = "BLENDER_EEVEE" <---------- Change BLENDER_EEVEE to BLENDER_EEVEE_NEXT
1394 try:

After fix it should look like this.

bpy.context.scene.render.engine = "BLENDER_EEVEE_NEXT"

Then save the file and relaunch blender. It should work

or replace your "innit.py" file with [This one](https://docs.google.com/uc?export=download&id=1QPoyvJqbHpie5qmmkSMfsU_Hde1WzbZa) replace the file with the mentioned above

**Comment by ghulamshabbir631** [comment]
I also cannot import models
A python error coming

**Comment by PadreZippo** [comment]
Fixed in **v1.7.0**. The importer now detects the available render engine at runtime — it uses **EEVEE Next** on Blender 4.x and falls back to **EEVEE** on older versions — so importing models works on Blender 4.2+ (including 4.4/4.5). Please update to the latest release: https://github.com/sketchfab/blender-plugin/releases/tag/1.7.0

Closing as resolved; please reopen if you still hit this on 1.7.0. Thanks for the report! 🙏
