### ISSUE TITLE
Bllender 4.1 error when trying to enable addon.

### ISSUE THREAD

**Issue by TakenRaccoon** [sketchfab/blender-plugin#157]
`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 444, in enable
    mod.register()
  File "C:\Users\ivans\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\sketchfab-plugin-1-6-1\__init__.py", line 2406, in register
    updateCacheDirectory(None, context=bpy.context)
  File "C:\Users\ivans\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\sketchfab-plugin-1-6-1\__init__.py", line 2296, in updateCacheDirectory
    if not os.path.exists(Config.SKETCHFAB_TEMP_DIR): os.makedirs(Config.SKETCHFAB_TEMP_DIR)
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'H:\\'
`

**Comment by Raymon-del2** [comment]
same

**Comment by 18038188969** [comment]
me too

**Comment by PadreZippo** [comment]
Fixed in **v1.7.1**. The add-on no longer crashes during registration when the download/cache directory can't be created (denied permissions, missing drive, unusual path characters) — it now falls back to the system temp directory and stays enabled. Please update: https://github.com/sketchfab/blender-plugin/releases/tag/1.7.1

Closing as resolved; reopen if it persists on 1.7.1. Thanks for the report! 🙏
