### ISSUE TITLE
no preview+error import

### ISSUE THREAD

**Issue by florentlebrun** [sketchfab/blender-plugin#18]
seems like I can't see object preview on 2.91. When i click the import button on a blank preview i get this error message.
 
Python: Traceback (most recent call last):
  File "C:\Users\ws\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\sketchfab-plugin-1-2-2\__init__.py", line 1178, in execute
    skfb_api.download_model(self.model_uid)
  File "C:\Users\ws\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\sketchfab-plugin-1-2-2\__init__.py", line 269, in download_model
    self.get_archive(skfb_model.download_url)
  File "C:\Users\ws\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\sketchfab-plugin-1-2-2\__init__.py", line 304, in get_archive
    os.makedirs(temp_dir)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 3 more times]
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\flore'

location: <unknown location>:-1

**Comment by loicSketchfab** [comment]
Hi @florentlebrun :wave: 

This seems new to me... Did you already manage to solve your issue ?

Given the logs, it seems that we don't manage to create the temporary directory we use to download archives from Sketchfab before importing them back into Blender. What seems strange is that your directory "AppData" - where the plugin is installed - is located in `C:\Users\ws\AppData\`, while we are trying to write the archive somewhere in `C:\Users\flore`.

Did you maybe install the plugin and/or Blender with a different user (ws) than the one you are currently using (flore) ? And if so, could you please try doing the same operation with the user flore ?

It's a case we've not seen previously, but if this does not come from an error on your side but a real usecase, we'll probably look into it :+1:

**Comment by florentlebrun** [comment]
hi,

ok seems pretty weird cause I reinstalled the addon on my new computer and didnt notice it was still trying to archive in my old folder, gonna try to fix that thanks

**Comment by kelheor** [comment]
I have the same issue. When I run Blender as administrator it worked but created another folder in C://Users. After some search I found that sometimes Windows cuts user names for online-based accounts (not local ones), so my user folder became "kelhe" instead of "kelheor" and Blender without admin rights can't create a new folder "kelheor" and it's not addressing to folder "kelhe". The solution might be adding an option to change the download path for models.
