### ISSUE TITLE
this error pops up before letting me use it

### ISSUE THREAD

**Issue by amanwaliaorg** [sketchfab/blender-plugin#38]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\Aman Walia\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\sketchfab-plugin-1-4-0\__init__.py", line 1870, in register
    bpy.utils.register_class(cls)
ValueError: bpy_struct "SketchfabBrowserProps" registration error: sort_by could not register

**Comment by DIY-Blub** [comment]
same problem here: when activating the addon, the error message appears and the addon remains inactive.
also with Blender Version 2.82 on Linux Mint 20.1 / Cinnamon 64-bit (Package Base: Ubuntu Focal)

**Comment by Baszczer** [comment]
Same here. Ubuntu 20.04. 
1.3.1 works fine.
