### ISSUE TITLE
Issue installing on 2.83

### ISSUE THREAD

**Issue by TomasHradcky** [sketchfab/blender-plugin#42]
I get this when attempting to install on 2.83.16 - it seems to be okay on 2.93Lts. I'm running Osx 10.13 High Sierra on a Mac Pro.

--------------------

Original exception was:
TypeError: EnumProperty(...): 'default' can't be set when 'items' is a function
Exception in module register(): /Users/TomasHradcky/Library/Application Support/Blender/Hrad Scripts/addons/sketchfab-plugin-1-4-0/__init__.py
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/modules/addon_utils.py", line 382, in enable
    mod.register()
  File "/Users/TomasHradcky/Library/Application Support/Blender/Hrad Scripts/addons/sketchfab-plugin-1-4-0/__init__.py", line 1870, in register
    bpy.utils.register_class(cls)
ValueError: bpy_struct "SketchfabBrowserProps" registration error: sort_by could not register

--------------------

I had also tried installing in the default location for 2.83. I removed all existing attempts (this happened in Sketchfab version 1.3 as well, I just decided to not use the plugin at that time) each time an install was attempted.

Thank you for any help.
Tomás

**Comment by TomasHradcky** [comment]
Just installed 1.4.1 again with no luck on Blender 2.83. Is there an older version that work?

**Comment by AlexBeauregard18** [comment]
I had a similar problem, try installing version 1.4.0 instead of 1.4.1 
here is the link, just go a bit lower on the page and you will find the plugin. it just worked for me

https://github.com/sketchfab/blender-plugin/releases

**Comment by schroef** [comment]
Same issue, its kinda weird. Not 100% sure why its giving errors when a function i used to get items. This normally does work. For me on osx 1.3.0 was the only i got to work with bl 2.83

Ttried doing some minor adjustments, but that raised other issues.
