### ISSUE TITLE
Enable plugin fails: sketchfab-plugin-1-4-1; Blender 2.9.0; Windows 10.

### ISSUE THREAD

**Issue by DanChristos** [sketchfab/blender-plugin#48]
On Windows 10 I have Blender 2.9.0 and I'm trying to install Sketchfab plugin 1.4.1. Importing the plugin works fine, but when I try to activate it I get the following in the terminal:
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Dan Christos\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\sketchfab-plugin-1-4-1\__init__.py", line 38, in <module>
    from .blender.imp.gltf2_blender_gltf import *
  File "C:\Users\Dan Christos\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\sketchfab-plugin-1-4-1\blender\imp\gltf2_blender_gltf.py", line 17, in <module>
    from .gltf2_blender_scene import BlenderScene
  File "C:\Users\Dan Christos\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\sketchfab-plugin-1-4-1\blender\imp\gltf2_blender_scene.py", line 17, in <module>
    from .gltf2_blender_node import BlenderNode
  File "C:\Users\Dan Christos\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\sketchfab-plugin-1-4-1\blender\imp\gltf2_blender_node.py", line 18, in <module>
    from .gltf2_blender_mesh import BlenderMesh
  File "C:\Users\Dan Christos\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\sketchfab-plugin-1-4-1\blender\imp\gltf2_blender_mesh.py", line 23, in <module>
    from .gltf2_io_draco_compression_extension import decode_primitive
  File "C:\Users\Dan Christos\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\sketchfab-plugin-1-4-1\blender\imp\gltf2_io_draco_compression_extension.py", line 20, in <module>
    from io_scene_gltf2.io.com.gltf2_io_draco_compression_extension import dll_path
ModuleNotFoundError: No module named 'io_scene_gltf2.io.com.gltf2_io_draco_compression_extension'
```
![sketchfabpluginerror_LI](https://user-images.githubusercontent.com/64300836/131289620-18fc5152-4715-4443-9343-5b54ed303fa3.jpg)

**Comment by jbcaveman** [comment]
I have the exact same issue. I can install from the ZIP, but the same errors show when attempting to enable it.

**Comment by AalapHR** [comment]
I have the same issue on Blender 2.82a. Windows 10 Home (v21H1, b19043.1237)

**Comment by loicSketchfab** [comment]
Closing this issue given version [1.5.0](https://github.com/sketchfab/blender-plugin/releases/tag/1.5.0) of the addon (2.83 to 3.2a, see release notes for more info).
