### ISSUE TITLE
Won't upload at all to Team Account

### ISSUE THREAD

**Issue by chippwalters** [sketchfab/blender-plugin#75]
![image](https://user-images.githubusercontent.com/7595271/165240970-5fbe87f6-51ef-4046-a6ad-4984a080f26c.png)

Uploads fine to my pro account but het this message when trying to upload to Team accouint.

`
Info: Saved "Sketchfab_2022_04_26_02_00_10.blend"
Info: Saved "Sketchfab_2022_04_26_02_00_10.blend"
Exception ignored in: <function Pool.__del__ at 0x0000022522FFD510>
Traceback (most recent call last):
  File "C:\Users\chipp\Downloads\blender-3.1.0-windows-x64\3.1\python\lib\multiprocessing\pool.py", line 268, in __del__
  File "C:\Users\chipp\Downloads\blender-3.1.0-windows-x64\3.1\python\lib\multiprocessing\queues.py", line 372, in put
AttributeError: 'NoneType' object has no attribute 'dumps'

Blender quit
Python: Traceback (most recent call last):
  File "C:\Users\chipp\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\sketchfab-plugin-1-5-0\__init__.py", line 2258, in execute
    upload_limit = Config.SKETCHFAB_UPLOAD_LIMITS["enterprise"]
KeyError: 'enterprise'

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\chipp\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\sketchfab-plugin-1-5-0\__init__.py", line 2258, in execute
    upload_limit = Config.SKETCHFAB_UPLOAD_LIMITS["enterprise"]
KeyError: 'enterprise'

location: <unknown location>:-1`

**Comment by PadreZippo** [comment]
We shipped a new version (1.6.0) of the Blender plugin, which will fix this issue: https://github.com/sketchfab/blender-plugin/releases

And, regarding Blender 4.0, this will fix the **_importer_**, as well as a couple other small bugs, but we have not yet updated the processing on our backend to handle Blender 4.0 .blend files, so the **_exporter_** feature still won't work yet. If you need to export, we recommend staying on 3.6.1 LTS or manually exporting GLB files until we update our processing for Blender 4.0 .blend files.
