### ISSUE TITLE
Blender 3.1 Can not install add-on

### ISSUE THREAD

**Issue by guyjayy** [sketchfab/blender-plugin#87]
Error:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 387, in enable
    mod.register()
  File "C:\Users\guyja\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\sketchfab-plugin-1-5-0\__init__.py", line 2428, in register
    updateCacheDirectory(None, context=bpy.context)
  File "C:\Users\guyja\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\sketchfab-plugin-1-5-0\__init__.py", line 2318, in updateCacheDirectory
    if not os.path.exists(Config.SKETCHFAB_TEMP_DIR): os.makedirs(Config.SKETCHFAB_TEMP_DIR)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\'

**Comment by Aekschen** [comment]
I have the similar issue. I share my preferences between PC's and actually it is not updating the preference path.

**Comment by lajawi** [comment]
Happens on Blender version 3.3.3 too!

**Comment by PadreZippo** [comment]
Fixed in **v1.7.1**. The add-on no longer crashes during registration when the download/cache directory can't be created (denied permissions, missing drive, unusual path characters) — it now falls back to the system temp directory and stays enabled. Please update: https://github.com/sketchfab/blender-plugin/releases/tag/1.7.1

Closing as resolved; reopen if it persists on 1.7.1. Thanks for the report! 🙏
